### ISSUE TITLE
cargo test fails with rustc 1.13.0 (2c6933acc 2016-11-07)

### ISSUE THREAD

**Issue by ghost** [sahid/libvirt-rs#1]
<pre>
warning: unused manifest key: package.categories
    Updating registry `https://github.com/rust-lang/crates.io-index`
 Downloading libc v0.2.23
   Compiling libc v0.2.23
   Compiling virt v0.2.0 (file:///home/loic/software/libvirt/libvirt-rs)
error[E0308]: mismatched types
   --> src/connect.rs:439:21
    |
439 |                 cb: wrapper,
    |                     ^^^^^^^ expected unsafe fn, found normal fn
    |
    = note: expected type `unsafe extern "C" fn(*mut connect::sys::virConnectCredential, u32, *mut typedparam::libc::c_void) -> i32`
    = note:    found type `extern "C" fn(*mut connect::sys::virConnectCredential, u32, *mut typedparam::libc::c_void) -> i32 {connect::ConnectAuth::to_cstruct::wrapper}`

error[E0308]: mismatched types
   --> src/connect.rs:439:21
    |
439 |                 cb: wrapper,
    |                     ^^^^^^^ expected unsafe fn, found normal fn
    |
    = note: expected type `unsafe extern "C" fn(*mut connect::sys::virConnectCredential, u32, *mut typedparam::libc::c_void) -> i32`
    = note:    found type `extern "C" fn(*mut connect::sys::virConnectCredential, u32, *mut typedparam::libc::c_void) -> i32 {connect::ConnectAuth::to_cstruct::wrapper}`

error: aborting due to previous error

error: aborting due to previous error

Build failed, waiting for other jobs to finish...
error: Could not compile `virt`.

</pre>

**Comment by sahid** [comment]
Ok so it seems that the version of rustc upper than 1.13.0 is smarter so it can detected that the method is well marked as unsafe because it includes the block "unsafe".

To fix the issue I had to define the method as unsafe and remove the block unsafe inside the method.


I sent a pull request:  https://github.com/sahid/libvirt-rs/pull/4

@dachary can you have a look?

Thanks
