### ISSUE TITLE
Feature request: Implement Error trait and Display trait for Error

### ISSUE THREAD

**Issue by farodin91** [sahid/libvirt-rs#6]

**Comment by sahid** [comment]
Hello @farodin91, 

Thanks for this proposal, regarding https://doc.rust-lang.org/book/error-handling.html#advice-for-library-writers that seems something expected.

I was planing to work on that part, is that OK or did you want to work on it?

**Comment by farodin91** [comment]
I could do this, if you want.

**Comment by sahid** [comment]
Sure you can :) I just made a cleanup of that module.
